name: pain-weekly
on:
  schedule:
    # Mondays 07:00 UTC = 12:30 IST (adjust as needed)
    - cron: "0 7 * * MON"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: "587"
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          NCBI_TOOL: pain-weekly-bot
          NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}
          # Optional:
          # NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
