# .github/workflows/pain-weekly.yml
name: pain-weekly
on:
  schedule:
    - cron: "0 7 * * MON"   # Mondays 12:30 IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot (builds abstracts.html + sends email)
        run: python bot.py
        env:
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          NCBI_TOOL: pain-weekly-bot
          NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}
          ABSTRACTS_BASE_URL: ${{ secrets.ABSTRACTS_BASE_URL }}
  # (Optional) add your deploy-to-Pages job here or use the separate deploy workflow I shared earlier
